namespace: timnormark-com-staging

replicaCount: 1

image:
  repository: 123456789012.dkr.ecr.eu-north-1.amazonaws.com/timnormark-com
  tag: main
  digest: ""
  pullPolicy: IfNotPresent

gateway:
  enabled: true
  route:
    hostnames:
      - staging.timnormark.example.com

env:
  - name: APP_ENV
    value: staging
